### ISSUE TITLE
Give credit to the creator you copied the code from

### ISSUE THREAD

**Issue by vink-sis** [llSourcell/Q-Learning-for-Trading#1]
Your content: https://github.com/llSourcell/Q-Learning-for-Trading

Original content: https://github.com/ShuaiW/teach-machine-to-trade (@ShuaiW)

It's such a shame that you are running an entire curriculum using code lifted from other people's repositories. __The least__ you could do is give credit to them.

I know it's not a breach of Github's T&S but I expect you to have a decent code of ethics. You don't need to be original and expert but at least be nice and humble. A big chunk of your videos is about finding motivation and being smart about learning. Surely you don't want to come across as a hypocrite.

**Comment by llSourcell** [comment]
1 - i havent promoted this yet, its still a work in progress, thats why i haven't filled out the readme yet (including the credit) 
2 - i credit every single author whos code i use, check every single repo ive ever promoted in a video, if credit is necessary, i've always given it
