### ISSUE TITLE
NotImplementedError by gym

### ISSUE THREAD

**Issue by init-22** [llSourcell/Q-Learning-for-Trading#7]
I am getting the following error which executing run.py
state = env.reset()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\gym\core.py", line 69, in reset
    raise NotImplementedError
NotImplementedError

Some people have suggested to change  env.reset() to env._reset() , I tried it as well but nothing works

**Comment by AntoineMath** [comment]
I'm a bit late but I changed _step() to step() and _reset() to reset() in TradingEnv class
